name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Extract commit hash
        id: extract_hash
        run: |
          # Extract the hash of the latest commit
          HASH=$(git rev-parse HEAD)
          echo "Commit hash: $HASH"
          echo "::set-output name=hash::$HASH"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'release-${{ steps.extract_hash.outputs.hash }}'
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
